name: vertical_weight_slider
description: This package provides easy-to-use and scrollable vertical weight slider. Compatible with Android & iOS & Web.
version: 2.4.0
homepage: https://github.com/mincheol-shin/vertical_weight_slider

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"
  

dependencies:
  flutter:
    sdk: flutter
  horizontal_blocked_scroll_physics: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
